/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import model.Adocao;
import model.Animal;
import model.Animal.Sexo;
import model.Atividade;
import model.Endereco;
import model.Ong;
import model.Pessoa;

/**
 *
 * @author tai
 */
public class AdocaoRealizada extends javax.swing.JPanel {

    private Ong ongLogada = null;
    private Adocao adocao = null;
    private Animal animal = null;

    /**
     * Creates new form SolicitacaoAdocao
     */
    public AdocaoRealizada(Ong ong, Animal animal) {
        initComponents();

        this.ongLogada = ong;
        this.animal = animal;

        jNomeDoPetTitle.setText(this.animal.getNome());
    }

    public AdocaoRealizada(Ong ong, Adocao adocao) {
        initComponents();

        this.ongLogada = ong;
        this.adocao = adocao;

        jNome1.setText(this.adocao.getAdotante().getNome());
        jCpf.setText(this.adocao.getAdotante().getCpf());
        jCep.setText(this.adocao.getAdotante().getEndereco().getCep());
        jEndereco.setText(this.adocao.getAdotante().getEndereco().getRua());
        jNumero.setText(Integer.toString(this.adocao.getAdotante().getEndereco().getNumero()));
        jCidade.setText(this.adocao.getAdotante().getEndereco().getCidade());
        jEstado.setText(this.adocao.getAdotante().getEndereco().getEstado());
        jEmail.setText(this.adocao.getAdotante().getEmail());
        jTelefone.setText(this.adocao.getAdotante().getTelefone());

        jNome1.setEnabled(false);
        jCpf.setEnabled(false);
        jCep.setEnabled(false);
        jEndereco.setEnabled(false);
        jNumero.setEnabled(false);
        jCidade.setEnabled(false);
        jEstado.setEnabled(false);
        jEmail.setEnabled(false);
        jTelefone.setEnabled(false);

        jNomeDoPetTitle.setText(this.adocao.getAnimal().getNome());
        jButtonSubmit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonSubmit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jEstado = new javax.swing.JTextField();
        jCpf = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jNome1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jCidade = new javax.swing.JTextField();
        jEndereco = new javax.swing.JTextField();
        jCep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jNumero = new javax.swing.JTextField();
        jTelefone = new javax.swing.JTextField();
        jNomeDoPetTitle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMaximumSize(new java.awt.Dimension(630, 470));
        setMinimumSize(new java.awt.Dimension(630, 470));
        setPreferredSize(new java.awt.Dimension(630, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(149, 127, 239));

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Cadastrar Pet");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTitle)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 100));

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSubmit.setBackground(new java.awt.Color(149, 127, 239));
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("CADASTRAR");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 439, 140, 30));

        jButton2.setBackground(new java.awt.Color(241, 69, 116));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 439, 140, 30));

        jLabel13.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        jLabel13.setText("ADOTAR O PET:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 26, -1, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridLayout(2, 1));
        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 214, 342, -1));

        jLabel29.setText("CPF:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 160, -1, -1));
        jPanel1.add(jEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 280, 50, -1));
        jPanel1.add(jCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, -1));

        jLabel25.setText("Nome do solicitante:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 120, -1, -1));
        jPanel1.add(jNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 117, 322, -1));

        jLabel8.setText("N:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 240, -1, -1));

        jLabel7.setText("Endereço:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 240, -1, -1));

        jLabel6.setText("CEP:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("INFORMAÇÕES DO ADOTANTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 62, -1, -1));

        jLabel9.setText("Cidade:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 280, -1, -1));
        jPanel1.add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 320, 200, -1));
        jPanel1.add(jCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 277, 200, -1));
        jPanel1.add(jEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 237, 200, -1));
        jPanel1.add(jCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 197, 100, -1));

        jLabel12.setText("Telefone de Contato:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 366, -1, -1));

        jLabel11.setText("E-mail:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 323, 40, -1));

        jLabel10.setText("Estado:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 283, -1, -1));
        jPanel1.add(jNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 237, 50, -1));
        jPanel1.add(jTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 363, 200, -1));

        jNomeDoPetTitle.setFont(new java.awt.Font("Fira Sans", 1, 13)); // NOI18N
        jNomeDoPetTitle.setText("NOME_DO_PET");
        jPanel1.add(jNomeDoPetTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 26, -1, -1));

        jScrollPane4.setViewportView(jPanel1);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 630, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JPanel parentPanel = (JPanel) this.getParent();

        parentPanel.removeAll();

        if (this.animal != null) {
            JPanel animais = new AnimaisDaOng(this.ongLogada);
            parentPanel.add(animais, BorderLayout.CENTER);
        } else {
            JPanel adocoes = new AdocoesRealizadas(this.ongLogada);
            parentPanel.add(adocoes, BorderLayout.CENTER);
        }
        // Add new content to the mainPanel

        // Repaint and revalidate the mainPanel to reflect the changes
        parentPanel.repaint();
        parentPanel.revalidate();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("petcare");
        EntityManager em = emf.createEntityManager();

        String Nome1 = jNome1.getText();
        String Cpf = jCpf.getText();
        String Cep = jCep.getText();
        String Endereco = jEndereco.getText();
        String Numero = jNumero.getText();
        String Cidade = jCidade.getText();
        String Estado = jEstado.getText();
        String Email = jEmail.getText();
        String Telefone = jTelefone.getText();

        em.getTransaction().begin();
        this.ongLogada = em.find(Ong.class, this.ongLogada.getId());
        this.animal = em.find(Animal.class, this.animal.getId());

        Endereco endereco = new Endereco(Cep, Endereco, Integer.parseInt(Numero), Cidade, Estado);
        Set<Atividade> atividades = new HashSet<>();

        Pessoa adotante = new Pessoa(Nome1, Cpf, endereco, Telefone, Email, Pessoa.Papel.adotante, this.ongLogada, atividades);

        Adocao adocao = new Adocao(Adocao.Status.APROVADA, this.ongLogada, adotante, this.animal);
        
        Animal animalAtualizado = em.find(Animal.class, this.animal.getId());
        
        animalAtualizado.setJa_foi_adotado(Boolean.TRUE);

        em.persist(adotante);
        em.persist(adocao);
        em.getTransaction().commit();
        em.close();
        emf.close();

        JPanel parentPanel = (JPanel) this.getParent();

        parentPanel.removeAll();
        // Add new content to the mainPanel
        JPanel animais = new AnimaisDaOng(this.ongLogada);
        parentPanel.add(animais, BorderLayout.CENTER);

        // Repaint and revalidate the mainPanel to reflect the changes
        parentPanel.repaint();
        parentPanel.revalidate();
    }//GEN-LAST:event_jButtonSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JTextField jCep;
    private javax.swing.JTextField jCidade;
    private javax.swing.JTextField jCpf;
    private javax.swing.JTextField jEmail;
    private javax.swing.JTextField jEndereco;
    private javax.swing.JTextField jEstado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jNome1;
    private javax.swing.JLabel jNomeDoPetTitle;
    private javax.swing.JTextField jNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTelefone;
    // End of variables declaration//GEN-END:variables
}
